[package]
name = "fapolicy-analyzer"
description = "Analyzer support for fapolicyd"
license = "LGPL-3.0-or-later"
version = "0.3.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
confy = "0.4.0"
directories = "2.0.2"
lmdb-rkv = "0.14.0"
nom = "6.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

fapolicy-api = { version = "0.3.0", path = "../api" }
fapolicy-daemon = { version = "0.3", path = "../daemon" }
fapolicy-trust = { version = "0.3", path = "../trust" }
fapolicy-util = { version = "0.3", path = "../util" }
