[package]
name = "fapolicy-analyzer"
description = "Analyzer support for fapolicyd"
license = "MPL-2.0"
version = "0.4.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
nom = "6.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
chrono = "0.4"

fapolicy-api = { version = "0.4.0", path = "../api" }
fapolicy-daemon = { version = "0.4", path = "../daemon" }
fapolicy-rules = { version = "0.4", path = "../rules" }
fapolicy-trust = { version = "0.4", path = "../trust" }
