baseURL = 'https://ctc-oss.github.io/fapolicy-analyzer/'
languageCode = 'en-us'
title = 'File Access Policy Analyzer'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
# (Optional, default light) Sets color theme: light, dark or auto.
# Theme 'auto' switches between dark and light modes based on browser/os preferences
BookTheme = 'auto'
# (Optional, default docs) Specify section of content to render as menu
# You can also set value to "*" to render all sections to menu
BookSection = '*'
