[package]
name = "fapolicy-analyzer"
version = "0.0.1"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

[[bin]]
path = "crates/cli/main.rs"
name = "faa"

[lib]
path = "crates/core/src/lib.rs"

[[test]]
name = "integration"
path = "tests/trust_model_test.rs"

[workspace]
exclude = ["py"]
members = [
    "crates/api",
    "crates/common",
    "crates/fapolicyd",
]

[dependencies]
clap = "3.0.0-beta.2"
api = { path = "crates/api" }
common = { path = "crates/common" }
fapolicyd = { path = "crates/fapolicyd" }

[dependencies.nom]
version = "6.1.0"
