[package]
name = "fapolicy-tools"
description = "Tools to assist with the configuration and maintenance of fapolicyd"
license = "GPL-3.0-or-later"
version = "0.3.0"
edition = "2018"

[[bin]]
name = "init-trust-db"
path = "crates/tools/trustdb_init.rs"

[[test]]
name = "integration"
path = "tests/tests.rs"

[workspace]
members = [
    "crates/analyzer",
    "crates/daemon",
    "crates/pyo3",
    "crates/trust",
    "crates/util",
]

[dependencies]
clap = "3.0.0-beta.2"
lmdb-rkv = "0.14.0"
nom = "6.1.0"

fapolicy-api = { version = "0.3.0", path = "crates/api" }
fapolicy-analyzer = { version = "0.3.0", path = "crates/analyzer" }
fapolicy-daemon = { version = "0.3.0", path = "crates/daemon" }
fapolicy-trust = { version = "0.3.0", path = "crates/trust" }
