[package]
name = "fapolicy-analyzer"
version = "0.0.1"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

[[bin]]
path = "crates/core/main.rs"
name = "fa"

[[test]]
name = "integration"
path = "tests/trust_model_test.rs"

[workspace]
exclude = ["py"]
members = [
    "crates/common",
    "crates/fapolicyd"
]

[dependencies]
clap = "3.0.0-beta.2"
fapolicyd = { version = "0.0.1", path = "crates/fapolicyd" }
fapolicy-common = { version = "0.0.1", path = "crates/common" }
