[package]
name = "fapolicy-analyzer"
version = "0.0.3"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
data-encoding = "2.3.1"
ring = "0.16.19"
nom = "6.1.0"
dbus = "0.9.1"
lmdb-rkv = "0.14.0"
