[package]
name = "fapolicy-analyzer"
version = "0.0.1"
edition = "2018"

[lib]
path = "src/lib.rs"

[[test]]
name = "integration"
path = "tests/trust_model_test.rs"

[dependencies]
nom = "6.1.0"
data-encoding = "2.3.1"
ring = "0.16.19"
