[workspace]
members = [
    "crates/analyzer",
    "crates/app",
    "crates/auparse",
    "crates/daemon",
    "crates/pyo3",
    "crates/rules",
    "crates/tools",
    "crates/trust",
    "crates/util",
]
