[package]
name = "fapolicy-analyzer"
version = "0.0.0"
license = "GPL-3.0"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

[[bin]]
path = "crates/core/main.rs"
name = "fa"

[[test]]
name = "integration"
path = "tests/trust_model_test.rs"

[workspace]
exclude = ["py"]
members = ["crates/trust"]

[dependencies]
clap = "3.0.0-beta.2"
fapolicyd-trust = { version = "0.0.0", path = "crates/trust" }
