[workspace]
resolver = "2"
members = [
    "crates/analyzer",
    "crates/app",
    "crates/daemon",
    "crates/pyo3",
    "crates/rules",
    "crates/tools",
    "crates/trust",
    "crates/util",
]
