[package]
name = "fapolicy-analyzer"
version = "0.0.1"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

[[bin]]
path = "crates/cli/main.rs"
name = "faa"

[[test]]
name = "integration"
path = "tests/trust_model_test.rs"

[workspace]
exclude = ["py"]
members = [
    "crates/common",
    "crates/core",
    "crates/fapolicyd",
    "crates/rpm"
]

[lib]
path = "crates/core/src/lib.rs"

[dependencies]
clap = "3.0.0-beta.2"
core = { version = "0.0.1", path = "crates/core" }
common = { version = "0.0.1", path = "crates/common" }
fapolicyd = { version = "0.0.1", path = "crates/fapolicyd" }
rpm = { version = "0.0.1", path = "crates/rpm" }
