# prepare fapolicy analyzer installation
---

- name: set el8 platform variable
  set_fact:
    analyzer_platform: "{{ lookup('lines', 'echo el8') }}"
  when:
    - ansible_facts['distribution'] == "RedHat"

- name: set fc34 platform variable
  set_fact:
    analyzer_platform: "{{ lookup('lines', 'echo fc34') }}"
  when:
    - ansible_facts['distribution'] == "Fedora"

- name: format analyzer rpm url
  debug:
    msg: "{{ lookup('template', 'analyzer_url.j2') }}"
    verbosity: 0

# todo;; gpg signing
- name: install analyzer
  yum:
    state: present
    name:
      - "{{ lookup('template', 'analyzer_url.j2') }}"
    disable_gpg_check: yes

- name: update gtk mimes
  shell: |
    update-mime-database /usr/share/mime
    gdk-pixbuf-query-loaders-64 --update-cache
