[package]
name = "fapolicy-util"
description = "Utility crate for fapolicyd"
license = "MPL-2.0"
version = "0.4.1"
edition = "2021"

[dependencies]
thiserror = "1.0"
nom = "7.1"
digest = "0.10"
sha2 = "0.10"
