[package]
name = "fapolicy-util"
description = "Utility crate for fapolicyd"
license = "MPL-2.0"
version = "0.4.0"
edition = "2018"

[package.metadata]
msrv = "1.54.0"

[dependencies]
data-encoding = "2.3.1"
ring = "0.16.19"
thiserror = "1.0"
