[package]
name = "fapolicy-analyzer-python"
version = "0.0.3"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.fapolicy-analyzer]
path = ".."

[dependencies.pyo3]
version = "0.12.1"
features = [ "extension-module",]
