[package]
name = "fapolicy-auparse-sys"
description = "Native bindings for audit parsing"
license = "MPL-2.0"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = ">=0.63"

[dependencies]
thiserror = "1"
