[package]
name = "fapolicy-auparse-sys"
description = "Native bindings for audit parsing"
license = "MPL-2.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"

[build-dependencies]
bindgen = ">=0.69"
shlex = "1.3.0"

[dependencies]
thiserror = "1"
