[package]
name = "fapolicy-rules"
description = "Rule support for fapolicyd"
license = "MPL-2.0"
version = "0.4.0"
edition = "2018"

[package.metadata]
msrv = "1.54.0"

[lib]
path = "src/lib.rs"

[dependencies]
nom = "6.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
