[package]
name = "fapolicy-rules"
description = "Rule support for fapolicyd"
license = "MPL-2.0"
version = "0.4.2"
edition = "2018"

[lib]
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.3"

[dependencies]
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
