# Install any missing plugins
required_plugins = %w( vagrant-vbguest vagrant-proxyconf vagrant-registration )
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  #config.vm.box_version = "3.4.4"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vbguest.auto_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  rpm_url = ENV['rpm_url']

  config.proxy.enabled = true
  config.proxy.http = ENV['http_proxy']
  config.proxy.https = ENV['https_proxy']
  config.proxy.no_proxy = "localhost,127.0.0.1"

  # RHSM BITS using the vagrant-registration plugin
  config.registration.proxy = ENV['http_proxy']
  config.registration.username = ENV['RHSM_USERNAME']
  config.registration.password = ENV['RHSM_PASSWORD']
  #config.registration.pools = ['pool1', 'pool2']
  config.registration.unregister_on_halt = false

  env = "prod"
  git_branch = "origin/master"
  if ENV['ENV'] == 'dev'
    if ENV['GIT_BRANCH']
      git_branch = ENV['GIT_BRANCH']
    end
    env = "dev"
    config.vbguest.auto_update = true
    config.vm.synced_folder ".shared/", "/shared", type: "virtualbox"
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../demo/site.yml"
    ansible.extra_vars = {
      env: env,
      git_branch: git_branch,
      rpm_url: rpm_url
    }
  end
end
