---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - role: system
    - role: develop
      when: env == 'dev'

- name: Configure
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - fapolicyd
    - filesystem
    - analyzer
    - users

- name: Simulate
  hosts: all
  gather_facts: no
  become: no
  roles:
    - events
