---
- name: Prepare
  hosts: all
  become: yes
  roles:
    - role: system
    - role: develop
      when: env == 'dev'

- name: Configure
  hosts: all
  become: yes
  roles:
    - users
    - fapolicyd
    - filesystem
    - role: analyzer
      when: env != 'dev'

- name: Simulate
  hosts: all
  gather_facts: no
  become: no
  roles:
    - events
