# Copyright Concurrent Technologies Corporation 2021
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# install and initialize dependencies
---
- name: install misc requirements common to the RedHat family
  yum:
    state: present
    name:
      - nano
      - which
      - xorg-x11-xauth
      - dbus-x11
      - dconf
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: install misc requirements that are Fedora 34 specific
  yum:
    state: present
    name:
      - polkit-gnome
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] == "34"

- name: share vagrant user xauthority globally
  lineinfile:
    state: present
    line: "export XAUTHORITY=/home/vagrant/.Xauthority"
    path: /etc/profile

- name: "add {{ vagrant_user }} to systemd-journal group"
  user:
    name: "{{ vagrant_user }}"
    groups: systemd-journal
    append: yes

- name: generate dconf dbs
  shell: |
    dconf update

- name: rotate journald
  shell: |
    journalctl --rotate
