# install and initialize dependencies
---
- name: install misc requirements common to the RedHat family
  yum:
    state: present
    name:
      - nano
      - which
      - xorg-x11-xauth
      - dbus-x11
      - dconf
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: install misc requirements that are Fedora 34 specific
  yum:
    state: present
    name:
      - polkit-gnome
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] == "34"

- name: share vagrant user xauthority globally
  lineinfile:
    state: present
    line: "export XAUTHORITY=/home/vagrant/.Xauthority"
    path: /etc/profile

- name: "add {{ vagrant_user }} to systemd-journal group"
  user:
    name: "{{ vagrant_user }}"
    groups: systemd-journal
    append: yes

- name: generate dconf dbs
  shell: |
    dconf update

- name: rotate journald
  shell: |
    journalctl --rotate
