# Copyright Concurrent Technologies Corporation 2021
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

analyzer_repo: ctc-oss/fapolicy-analyzer
analyzer_version: 0.2.0
analyzer_release: 1
analyzer_rpm_download_url_format: "https://github.com/{{analyzer_repo}}/releases/download/v{{analyzer_version}}/fapolicy-analyzer-{{analyzer_version}}-{{analyzer_release}}.fc34.x86_64.rpm"
analyzer_rpm_download_url: "{{ lookup('env', 'rpm_url') | default(analyzer_rpm_download_url_format, True) }}"
vagrant_user: vagrant
default_git_branch: "origin/master"
git_branch: "{{ lookup('env', 'git_branch') | default(default_git_branch, True) }}"
env: "{{ lookup('env', 'env') | default('prod', True) }}"
