vagrant_user: vagrant
default_git_branch: "origin/master"
git_branch: "{{ lookup('env', 'git_branch') | default(default_git_branch, True) }}"
env: "{{ lookup('env', 'env') | default('prod', True) }}"
