# create demonstration users and groups
---
- name: create demo users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: users
    comment: "demo user"
  loop:
    - { name: bob, uid: 1001 }
    - { name: alice, uid: 1002 }
    - { name: carol, uid: 1003 }
    - { name: dave, uid: 1004 }
    - { name: eve, uid: 1005 }
    - { name: mallory, uid: 1006 }
    - { name: trudy, uid: 1007 }

- name: create demo groups
  group:
    name: "{{ item.name }}"
    state: present
  loop:
    - { name: accountant }
    - { name: developer }
    - { name: sysadmin }

- name: add dave to developer group
  user:
    name: dave
    groups: developer
    append: yes

- name: add trudy to sysadmin group
  user:
    name: trudy
    groups: sysadmin
    append: yes
