ARG image=fedora:rawhide
FROM $image AS build-stage

RUN grep -e "^Red Hat Enterprise Linux" /etc/redhat-release  \
 && RELEASE=$(grep -oE "[0-9]+\.[0-9]+" /etc/redhat-release) \
 && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
 || true

RUN dnf install -y rpm-build rpmdevtools dnf-plugins-core python3-pip nano rust-packaging

WORKDIR /root/rpmbuild

RUN mkdir -p {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
COPY scripts/srpm/fapolicy-analyzer.spec        SPECS/

RUN dnf -y builddep SPECS/fapolicy-analyzer.spec

COPY fapolicy-analyzer.tar.gz SOURCES/
COPY crates.tar.gz            SOURCES/
COPY scripts/srpm/build.sh ./build.sh

WORKDIR /root/rpmbuild

CMD ./build.sh
