ARG image=fedora:rawhide
FROM $image AS build-stage

RUN dnf install -y rpm-build dnf-plugins-core python3-pip nano

WORKDIR /root/rpmbuild

RUN mkdir -p {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
COPY scripts/srpm/fapolicy-analyzer.spec        SPECS/

RUN dnf -y builddep SPECS/fapolicy-analyzer.spec

COPY fapolicy-analyzer.tar.gz SOURCES/
COPY vendor-rs.tar.gz         SOURCES/
COPY scripts/srpm/build.sh    ./build.sh

WORKDIR /root/rpmbuild

CMD ./build.sh
