FROM fedora:rawhide AS build-stage

RUN dnf install -y rpm-build rpmdevtools dnf-plugins-core python3-pip nano rust-packaging

WORKDIR /root/rpmbuild

RUN mkdir -p {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
COPY scripts/srpm/fapolicy-analyzer.spec        SPECS/

RUN dnf -y builddep SPECS/fapolicy-analyzer.spec

COPY fapolicy-analyzer.tar.gz SOURCES/
COPY crates.tar.gz            SOURCES/
COPY scripts/srpm/build.sh ./build.sh

WORKDIR /root/rpmbuild

CMD ./build.sh
