# install development requirements, and create a build
---
- name: install development requirements
  yum:
    state: present
    name:
      - bzip2
      - bzip2-devel
      - cairo
      - cairo-devel
      - cairo-gobject-devel
      - dbus-devel
      - gcc
      - git
      - glade
      - gobject-introspection-devel
      - openssl-devel
      - python3-cairo-devel
      - python3-wheel
      - python-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - tk-devel
      - zlib-devel

- name: install rust for the vagrant user
  become: yes
  become_user: "{{ vagrant_user }}"
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  changed_when: false

- name: install pipenv for the vagrant user
  become: yes
  become_user: "{{ vagrant_user }}"
  pip:
    name: pipenv
    extra_args: --user

- name: source code checkout
  become: yes
  become_user: "{{ vagrant_user }}"
  git:
    repo: 'https://github.com/ctc-oss/fapolicy-analyzer.git'
    dest: "/shared/{{ vagrant_user }}/git/fapolicy-analyzer"

- name: create python environment
  become: yes
  become_user: "{{ vagrant_user }}"
  command: chdir="/shared/{{ vagrant_user }}/git/fapolicy-analyzer/" pipenv install --dev

- name: check if fapolicyd service exists
  stat: path=/etc/systemd/system/multi-user.target.wants/fapolicyd.service
  register: fapolicyd_service_status

- name: stop fapolicyd service
  systemd:
    name: fapolicyd
    state: stopped
  when: fapolicyd_service_status.stat.exists

- name: build the project
  become: yes
  become_user: "{{ vagrant_user }}"
  command: chdir="/shared/{{ vagrant_user }}/git/fapolicy-analyzer/" pipenv run python setup.py develop

- name: create symbolic link to shared repo
  file:
    src: "/shared/{{ vagrant_user }}/git"
    dest: "/home/{{ vagrant_user }}/git"
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    state: link

- name: start fapolicyd service
  systemd:
    name: fapolicyd
    state: started
  when: fapolicyd_service_status.stat.exists
