Vagrant.configure("2") do |config|
  config.vm.box = "fedora/34-cloud-base"
  config.vm.box_version = "34.20210423.0"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provision "shell", env: {"http_proxy" => "$http_proxy"}, env: {"https_proxy" => "$https_proxy"}, inline: <<-SHELL
    yum install -y python3 which gtk3 xorg-x11-xauth nano fapolicyd
    echo "export XAUTHORITY=/home/vagrant/.Xauthority" >> /etc/profile
    yum install -y https://github.com/ctc-oss/fapolicy-analyzer/releases/download/v0.2.0-rc4/fapolicy-analyzer-0.2.0-0.rc4.fc34.x86_64.rpm
    systemctl enable fapolicyd
    systemctl start fapolicyd
  SHELL
end
