.\" Manpage for the fapolicy-analyzer Profiler CLI.
.TH man 8 "30 Dec 2023" "1.0" "fapolicy-analyzer-cli-profiler man page"
.SH NAME
fapolicy-analyzer-cli-profiler \- Program execution and analysis CLI for fapolicyd
.SH SYNOPSIS
Provides command line tool to execute and assist with analysis of applications using fapolicyd.
.P
This tool allows a command to be executed with fapolicyd in permissie mode to capture and analyze logged file access events.

.SH DESCRIPTION
Provides File Access Policy Analyzer profiler functionality from the command line.

.SH SEE ALSO
fapolicy-analyzer(8), fapolicyd(8)

.SH BUGS
No known bugs.
