.\" Manpage for the fapolicy-analyzer Rules CLI.
.TH man 8 "30 Dec 2023" "1.0" "fapolicy-analyzer-cli-rules man page"
.SH NAME
fapolicy-analyzer-cli-rules \- Configuration and analysis CLI for fapolicyd rule files
.SH SYNOPSIS
Provides command line tool to assist with the configuration and management of fapolicyd rules.
.P
This tool allows validation and compilation of fapolicyd rule files.

.SH DESCRIPTION
Provides File Access Policy Analyzer rules functionality from the command line.

.SH SEE ALSO
fapolicy-analyzer(8), fapolicyd.rules(5), fapolicyd(8)

.SH BUGS
No known bugs.
