.\" Manpage for the fapolicy-analyzer Trust CLI.
.TH man 8 "30 Dec 2023" "1.0" "fapolicy-analyzer-cli-trust man page"
.SH NAME
fapolicy-analyzer-cli-trust \- Configuration and analysis CLI for fapolicyd trust entries
.SH SYNOPSIS
Provides command line tool to assist with the configuration and management of fapolicyd trust.
.P
This tool allows setup and customization of trust entries suitable for a variety of use cases.

.SH DESCRIPTION
Provides File Access Policy Analyzer trust functionality from the command line.

.SH SEE ALSO
fapolicy-analyzer(8), fapolicyd.trust(5), fapolicyd(8)

.SH BUGS
No known bugs.
