.\" Manpage for fapolicy-analyzer.
.TH man 8 "20 Dec 2022" "1.0" "nuseradd man page"
.SH NAME
fapolicy-analyzer \- Configuration and management of fapolicyd
.SH SYNOPSIS
This application consists of several GUI components:
.P
  1. Trust Administration
.br
  2. Rule Administration
.br
  3. Policy Profiling
.br
  4. Log Analysis
.SH DESCRIPTION
File Access Policy Analyzer is a GUI tool to assist with the configuration and management of fapolicyd.
.SH OPTIONS
.TP
.B \-v, \-\-verbose
Enable verbose mode to increase logging output.
.SH SEE ALSO
fapolicyd(8), fapolicyd.rules(5), fapolicyd.trust(5), fapolicyd-cli(1)
.SH BUGS
No known bugs.

