[package]
name = "fapolicy-daemon"
description = "Bindings to fapolicyd"
license = "MPL-2.0"
version = "0.4.0"
edition = "2018"

[package.metadata]
msrv = "1.54.0"

[dependencies]
nom = "6.1.0"
thiserror = "1.0"
fapolicy-api = { version = "*", path = "../api" }

[dependencies.dbus]
version = "0.9"
optional = true

[features]
default = []
systemd = ["dbus"]
