[package]
name = "fapolicy-daemon"
description = "Bindings to fapolicyd"
license = "MPL-2.0"
version = "0.4.0"
edition = "2018"

[dependencies]
nom = "7.1"
thiserror = "1.0"
fapolicy-api = { version = "*", path = "../api" }
dbus = "0.9"
