# configure demonstration fapolicyd rules and trust entries
---
- name: install fapolicyd
  yum:
    state: present
    name:
      - fapolicyd

- name: override fapolicy configuration
  copy:
    src: "{{ item.src }}"
    dest: "/etc/fapolicyd/{{ item.dest }}"
  loop:
    - { src: fapolicyd.conf.md, dest: fapolicyd.conf }
    - { src: demo.trust, dest: fapolicyd.trust }

- name: "Add {{ vagrant_user }} to fapolicyd group"
  user:
    name: "{{ vagrant_user }}"
    groups: fapolicyd
    append: yes

- name: Ensure rules.d does not exist
  file:
    path: /etc/fapolicyd/rules.d
    state: absent

- name: Install demonstration rules [RHEL8]
  copy:
    src: "rules.d"
    dest: "/etc/fapolicyd"
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: Install demonstration rules [FC34]
  copy:
    src: "trust.rules.md"
    dest: "/etc/fapolicyd/fapolicyd.rules"
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] == "34"

- name: Add RuntimeMaxSec to fapolicyd service
  lineinfile:
    path: /usr/lib/systemd/system/fapolicyd.service
    regexp: '^RuntimeMaxSec='
    insertafter: '^ExecStart=/usr/sbin/fapolicyd'
    line: 'RuntimeMaxSec=120'
    state: present

- name: Disable restart of fapolicyd service
  lineinfile:
    path: /usr/lib/systemd/system/fapolicyd.service
    regexp: '^Restart=.*'
    state: absent

- name: Enable fapolicyd service
  systemd:
    name: fapolicyd
    state: restarted
    daemon_reload: yes
    enabled: true
