# configure demonstration fapolicyd rules and trust entries
---
- name: install fapolicyd
  yum:
    state: present
    name:
      - fapolicyd

- name: override fapolicy configuration
  copy:
    src: "{{ item.src }}"
    dest: "/etc/fapolicyd/{{ item.dest }}"
  loop:
    - { src: fapolicyd.conf.md, dest: fapolicyd.conf }
    - { src: demo.trust, dest: fapolicyd.trust }

- name: enable fapolicyd service
  systemd:
    name: fapolicyd
    state: restarted
    enabled: true

- name: "Add {{ vagrant_user }} to fapolicyd group"
  user:
    name: "{{ vagrant_user }}"
    groups: fapolicyd
    append: yes

- name: Install demonstration rules.d
  copy:
    src: "{{ item.src }}"
    dest: "/etc/fapolicyd/{{ item.dest }}"
  loop:
    - { src: trust.compiled.rules, dest: compiled.rules }
    - { src: rules.d, dest: rules.d }
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: Install demonstration fapolicyd.rules [LEGACY]
  copy:
    src: "trust.rules.md"
    dest: "/etc/fapolicyd/fapolicyd.rules"
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] == "34"
