# Copyright Concurrent Technologies Corporation 2021
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# configure demonstration fapolicyd rules and trust entries
---
- name: install fapolicyd
  yum:
    state: present
    name:
      - fapolicyd

- name: override fapolicy configuration
  copy:
    src: "{{ item.src }}"
    dest: "/etc/fapolicyd/{{ item.dest }}"
  loop:
    - { src: fapolicyd.conf.md, dest: fapolicyd.conf }
    - { src: trust.rules.md, dest: fapolicyd.rules }
    - { src: demo.trust, dest: fapolicyd.trust }

- name: enable fapolicyd service
  systemd:
    name: fapolicyd
    state: restarted
    enabled: true

- name: "Add {{ vagrant_user }} to fapolicyd group"
  user:
    name: "{{ vagrant_user }}"
    groups: fapolicyd
    append: yes
