[package]
name = "fapolicy-pyo3"
description = "Python bindings for the fapolicy-analyzer"
license = "LGPL-3.0-or-later"
version = "0.3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.fapolicy-analyzer]
path = "../analyzer"

[dependencies.pyo3]
version = "0.14.2"
