[package]
name = "fapolicy-pyo3"
description = "Python bindings for the fapolicy-analyzer"
license = "LGPL-3.0-or-later"
version = "0.3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.14.2"
fapolicy-analyzer = { version = "0.3", path = "../analyzer" }
fapolicy-daemon = { version = "0.3", path = "../daemon" }
fapolicy-trust = { version = "0.3", path = "../trust" }
