[package]
name = "fapolicy-pyo3"
description = "Python bindings for the fapolicy-analyzer"
license = "MPL-2.0"
version = "0.4.0"
edition = "2018"

[package.metadata]
msrv = "1.54.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.14"

fapolicy-api = { version = "*", path = "../api" }
fapolicy-analyzer = { version = "*", path = "../analyzer" }
fapolicy-app = { version = "*", path = "../app" }
fapolicy-daemon = { version = "*", path = "../daemon", features = ["systemd"] }
fapolicy-rules = { version = "*", path = "../rules" }
fapolicy-trust = { version = "*", path = "../trust" }
