name: Check PR change log

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check:
    name: Check if towncrier change log entry is correct
    runs-on: ubuntu-latest
    steps:
      - uses: scientific-python/action-towncrier-changelog@0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_USERNAME: changelog-bot