on:
  push:
    branches:
      - 'master'
      - 'release/*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: Common CI

jobs:
  headers:
    name: License header check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Check for required headers
        run: |
          ! grep -R -L --exclude-dir=vendor \
            --include='*.py' --include='*.rs' --include='*.glade' --include='*.sh' \
            'Copyright Concurrent Technologies Corporation' *
