on:
  push:
    branches:
      - 'master'
      - 'release-*'
  pull_request:
    branches:
      - 'master'
      - 'release-*'

name: Common CI

jobs:
  headers:
    name: License header check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for required headers
        run: make header-check
