on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

name: Copr Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 'rockylinux:8.6'
    steps:
      - name: Enable EPEL
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

      - name: Dnf
        run: |
          dnf install -y git

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Strip ref to tag
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d/ -f3)

      - name: Install Copr CLI
        run: |
          dnf install -y copr-cli

      - name: Install Config
        run: |
          mkdir -p ~/.config
          echo  > ~/.config/copr <<EOF
            [copr-cli]
            username = ctc-oss
            login = ${COPR_API_LOGIN}
            token = ${COPR_API_TOKEN}
            copr_url = https://copr.fedorainfracloud.org
          EOF
        env:
          COPR_API_LOGIN: ${{ secrets.COPR_API_LOGIN }}
          COPR_API_TOKEN: ${{ secrets.COPR_API_TOKEN }}

      # run on tag or PR
      # fapolicy-analyzer:custom:master
      # fapolicy-analyzer:pr:${{ github.event.pull_request.number }}
      # fapolicy-analyzer:custom:${{ steps.tag_name.outputs.VERSION }}
      - name: Submit Build
        run: |
          copr-cli buildscm \
          --method make_srpm \
          --commit ${{ github.sha }} \
          --spec scripts/srpm/fapolicy-analyzer.spec \
          --clone-url ${{ github.server_url }}/${{ github.repository }} \
          fapolicy-analyzer:pr:${{ github.event.pull_request.number }}
