on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

name: Copr

jobs:
  build:
    name: Build ${{ matrix.props.name }}
    strategy:
      matrix:
        props:
          - {
            name: 'fc37',
            chroot: 'fedora-37-x86_64',
          }
          - {
            name: 'fc38',
            chroot: 'fedora-rawhide-x86_64',
          }
          - {
            name: 'el8',
            chroot: 'epel-8-x86_64',
          }
    runs-on: ubuntu-20.04
    container: 'rockylinux:8.6'
    steps:
      - name: Enable EPEL
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

      - name: Dnf
        run: |
          dnf install -y git

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Strip ref to tag
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d/ -f3)

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: srpm-artifacts
          workflow: rpm.yml
          path: /tmp

      - name: Install Copr CLI
        run: |
          dnf install -y copr-cli

      - name: Install Config
        run: |
          mkdir -p $HOME/.config
          echo "[copr-cli]" > $HOME/.config/copr 
          echo "username = ctc-oss" >> $HOME/.config/copr
          echo "login = ${COPR_LOGIN}" >> $HOME/.config/copr
          echo "token = ${COPR_TOKEN}" >> $HOME/.config/copr
          echo "copr_url = https://copr.fedorainfracloud.org" >> $HOME/.config/copr
        env:
          COPR_LOGIN: ${{ secrets.COPR_API_LOGIN }}
          COPR_TOKEN: ${{ secrets.COPR_API_TOKEN }}

      - name: debug
        run: |
          ls /tmp

      - name: Copr Release Build
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          copr-cli build --chroot ${{ matrix.props.chroot }} fapolicy-analyzer /tmp/fapolicy-analyzer-*.${{ matrix.props.name }}.src.rpm

      - name: Copr Latest Build
        if: github.ref == 'refs/heads/master'
        run: |
          copr-cli build --chroot ${{ matrix.props.chroot }} fapolicy-analyzer-latest /tmp/fapolicy-analyzer-*.${{ matrix.props.name }}.src.rpm

#      - name: Copr PR Build
#        if: github.event_name == 'pull_request'
#        run: |
#          copr-cli build --chroot ${{ matrix.props.chroot }} fapolicy-analyzer-latest:pr:${{ github.event.pull_request.number }} /tmp/fapolicy-analyzer-*.${{ matrix.props.name }}.src.rpm
