on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'rpm/test/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: foo

jobs:
  config:
    name: Install mock
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt install -y podman
      - run: podman run --privileged fedora:39
