on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'rpm/test/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: foo

jobs:
  config:
    name: Install mock
    runs-on: ubuntu-20.04
    steps:
      - run: curl -LO https://launchpadlibrarian.net/317625959/mock_1.3.2-2_all.deb
      - run: dpkg -i mock_1.3.2-2_all.deb
