on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'rpm/test/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: foo

jobs:
  config:
    name: Install mock
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt install -y podman
          ct=$(podman run -dt --privileged fedora:39)
          podman exec $ct dnf install -y mock
          podman exec $ct mock -r fedora-39-x86_64 --init