on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Build
    steps:
    - name: Install git
      run: |
        sudo apt update
        sudo apt install -y git

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Strip ref to tag
      id: tag_name
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d/ -f3)

    - uses: softprops/action-gh-release@v1
      name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.tag_name.outputs.VERSION }}
        tag_name: ${{ steps.tag_name.outputs.VERSION }}
        prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
        draft: true
