on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

name: Create RPM Release

jobs:
  build:
    strategy:
      matrix:
        platform: [ 'fedora:32', 'fedora:33', 'fedora:34' ]
    runs-on: ubuntu-latest
    container: ${{ matrix.platform }}
    name: Create RPM Release
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.52.0
          override: true

      - name: Install dnf requirements
        run: |
          dnf install -q -y python3 python3-devel python3-pip dbus-devel cairo-devel pkg-config which gobject-introspection-devel cairo-gobject-devel fedora-packager fedora-review
          dnf groupinstall -q -y "Development Tools"

      - name: Install pip requirements
        run: pip3 install pipenv wheel

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pipenv deploy
        run: pipenv install --system --deploy --dev
        working-directory: python

      - name: Generate tags
        run: |
          curl -so /usr/local/bin/git-rpm-version https://raw.githubusercontent.com/peterlundgren/git-rpm-version/master/git-rpm-version
          chmod +x /usr/local/bin/git-rpm-version
          git describe | cut -c 2- > DESCRIBE
          git-rpm-version -v HEAD  > VERSION
          git-rpm-version -r HEAD  > RELEASE
        working-directory: python

      - name: Build RPM
        id: rpm_build
        run: ../scripts/rpm/build.sh /tmp
        working-directory: python

      - name: Create Release notes
        run: |
          echo "Release Notes" >> release-notes
          echo "=============" >> release-notes

      - uses: softprops/action-gh-release@v1
        name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: release-notes
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
          draft: true
          files: |
            /tmp/*.rpm
