on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

name: Create RPM Release

jobs:
  build:
    strategy:
      matrix:
        platform: [ 'fedora:33', 'fedora:34' ]
    runs-on: ubuntu-latest
    container: ${{ matrix.platform }}
    name: Create RPM Release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install basic rpmbuild toolchain
        run: |
          dnf install -y rpm-build rpmdevtools dnf-plugins-core python3-jinja2-cli

      - name: Generate the standalone spec file from the template and args
        run: |
          mkdir -p "$HOME"/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          curl -so /usr/local/bin/git-rpm-version https://raw.githubusercontent.com/peterlundgren/git-rpm-version/master/git-rpm-version
          chmod +x /usr/local/bin/git-rpm-version
          FEDORA_VER="$(source /etc/os-release ; echo "$VERSION_ID")"
          GIT_COMMIT="$(git describe --match "v*" --abbrev=0 --candidates=0 || git rev-parse --verify HEAD)"
          RPM_VERSION="$(git-rpm-version -v HEAD)"
          RPM_RELEASE="$(git-rpm-version -r HEAD)"
          jinja2                          \
            -D fedora_ver=${FEDORA_VER}   \
            -D git_commit=${GIT_COMMIT}   \
            -D rpm_version=${RPM_VERSION} \
            -D rpm_release=${RPM_RELEASE} \
            fapolicy-analyzer.spec.j2 > "$HOME"/rpmbuild/SPECS/fapolicy-analyzer.spec
        working-directory: ${{ github.workspace }}/scripts/rpm

      - name: Download package source
        run: |
          spectool -gf ../SPECS/fapolicy-analyzer.spec \
        working-directory: ${{ home }}/rpmbuild/SOURCES

      - name: Install package build dependencies
        run: |
           dnf builddep fapolicy-analyzer.spec -y
        working-directory: ${{ home }}/rpmbuild/SPECS

      - name: Build the package
        run: |
           rpmbuild -ba fapolicy-analyzer.spec
        working-directory: ${{ home }}/rpmbuild/SPECS

      - name: Export the package
        run: |
          cp **/*.rpm "$RUNNER_TEMP"
        working-directory: ${{ home }}/rpmbuild

      - uses: softprops/action-gh-release@v1
        name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: release-notes
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
          draft: true
          files: |
            "$RUNNER_TEMP"/*.rpm
