on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'rpm/test/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: RPM

jobs:
  config:
    name: Load config matrix
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(cat .github/rpm-matrix.json | tr -d '\n' | tr -d ' ')"

  srpm:
    needs: [ config ]
    name: SRPM Build ${{ matrix.props.dist }}
    container: ${{ matrix.props.image }}
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJson(needs.config.outputs.matrix) }}
    steps:
      - name: Enable EPEL
        if: startsWith(matrix.props.dist, 'el')
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

      - name: Install Git
        run: dnf install -y git

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Strip ref to tag
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d/ -f3)

      # allows the git archive command to run within the repo
      - name: Add workspace as git safe directory
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Ensure spec version matches tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          spec_version=$(grep "Version:" ${{ matrix.props.spec }} | tr -s ' ' | cut -d' ' -f2)
          tag="${{ steps.tag_name.outputs.VERSION }}"
          tag_version="${tag#v}"
          echo "Got version $tag_version from git tag $tag"
          
          if [[ "$tag_version" == *-rc* ]] && [[ "$spec_version" != *~rc* ]]; then
            echo "The spec version ($spec_version) prerelease tag does not agree with git ($tag_version)"
            exit 1
          fi
          
          normalized_spec_version=$(echo "$spec_version" | tr "~" "-")
          if [[ ! "$tag_version" == "$normalized_spec_version" ]]; then
            echo "The spec version ($normalized_spec_version) does not agree with git ($tag_version)"
            exit 2
          fi
          
          echo "The spec version $spec_version is correct based on git tag $tag"

      - name: Patch spec with prerelease version
        #if: endsWith(github.ref, '/master')
        run: |
          spec_version=$(grep "Version:" ${{ matrix.props.spec }} | tr -s ' ' | cut -d' ' -f2)
          commit_number=$(git rev-list HEAD --count)
          patched_version="$spec_version~pre${commit_number}"
          sed -i "s#Version:\s*${spec_version}#Version: ${patched_version}#" ${{ matrix.props.spec }}

      - name: Install RPM build dependencies
        run: |
          dnf install -y make rpm rpmdevtools dnf-plugins-core

      - name: Install SRPM build dependencies
        run: |
          make -f .copr/Makefile dnf

      - name: Build SRPM
        run: |
          make -f .copr/Makefile srpm outdir=/tmp/archives spec=${{ matrix.props.spec }} OS_ID=${{ matrix.props.platform }}

      - name: Export tarballs
        run: |
          mkdir -p /tmp/archives
          mv vendor-rs.tar.gz         /tmp/archives/vendor-rs.$PLATFORM.tar.gz
          mv vendor-docs.tar.gz       /tmp/archives
          mv fapolicy-analyzer.tar.gz /tmp/archives
        env:
          PLATFORM: ${{ matrix.props.dist }}

      - name: Upload tarballs
        uses: actions/upload-artifact@v2
        with:
          name: tarball-artifacts
          path: |
            /tmp/archives/*.tar.gz

      - name: Upload SRPMs
        uses: actions/upload-artifact@v2
        with:
          name: srpm-artifacts
          path: |
            /tmp/archives/*.src.rpm

  copr:
    needs: [ config, srpm ]
    name: Copr Build ${{ matrix.props.dist }}
    if: startsWith(github.ref, 'refs/tags/v') || endsWith(github.ref, '/master')
    container: 'rockylinux:8.6'
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJson(needs.config.outputs.matrix) }}
    steps:
      - name: Enable EPEL
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

      - name: Dnf
        run: |
          dnf install -y git

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Strip ref to tag
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d/ -f3)

      - name: Download srpm artifacts
        uses: actions/download-artifact@v3
        with:
          name: srpm-artifacts
          path: /tmp/

      - name: Install Copr CLI
        run: |
          dnf install -y copr-cli

      - name: Install Config
        run: |
          mkdir -p $HOME/.config
          echo "[copr-cli]" > $HOME/.config/copr 
          echo "username = ctc-oss" >> $HOME/.config/copr
          echo "login = ${COPR_LOGIN}" >> $HOME/.config/copr
          echo "token = ${COPR_TOKEN}" >> $HOME/.config/copr
          echo "copr_url = https://copr.fedorainfracloud.org" >> $HOME/.config/copr
        env:
          COPR_LOGIN: ${{ secrets.COPR_API_LOGIN }}
          COPR_TOKEN: ${{ secrets.COPR_API_TOKEN }}

      - name: debug
        run: |
          ls /tmp

      - name: Copr Release Build
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          copr-cli build --chroot ${{ matrix.props.chroot }} fapolicy-analyzer /tmp/fapolicy-analyzer-*.${{ matrix.props.dist }}.src.rpm

      - name: Copr Latest Build
        if: endsWith(github.ref, '/master')
        run: |
          copr-cli build --chroot ${{ matrix.props.chroot }} fapolicy-analyzer-latest /tmp/fapolicy-analyzer-*.${{ matrix.props.dist }}.src.rpm

#      todo;; cant build PRs due to secrets not populating forks in the expected way
#      - name: Copr PR Build
#        if: github.event_name == 'pull_request'
#        run: |
#          copr-cli build --chroot ${{ matrix.props.chroot }} fapolicy-analyzer-latest:pr:${{ github.event.pull_request.number }} /tmp/fapolicy-analyzer-*.${{ matrix.props.dist }}.src.rpm

  rpm:
    needs: [ config, srpm ]
    name: Rebuild ${{ matrix.props.dist }}
    container: ${{ matrix.props.image }}
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJson(needs.config.outputs.matrix )}}
    steps:
      - uses: actions/checkout@v2

      - name: Download srpm artifacts
        uses: actions/download-artifact@v3
        with:
          name: srpm-artifacts
          path: /tmp/src/

      - name: Enable EPEL
        if: startsWith(matrix.props.dist, 'el')
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

      - name: Install RPM build dependencies
        run: |
          dnf install -y make rpm rpmdevtools dnf-plugins-core

      - name: Rebuild SRPM
        run: |
          dnf builddep -y ${{ matrix.props.spec }}
          rpmbuild --rebuild /tmp/src/fapolicy-analyzer-*.${{ matrix.props.dist }}.src.rpm

      - name: Export RPMs
        run: |
          mkdir -p /tmp/archives
          ls | grep -v debug | xargs mv -t /tmp/archives
        working-directory: /github/home/rpmbuild/RPMS/x86_64

      - name: Upload RPMs
        uses: actions/upload-artifact@v2
        with:
          name: rpm-artifacts
          path: |
            /tmp/archives/*.x86_64.rpm

  publish:
    needs: [ srpm, rpm, copr ]
    name: Publish
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Release Spec File
        run: |
          out=/tmp/archives/fapolicy-analyzer.spec
          base=https://github.com/$GITHUB_REPOSITORY/releases/download/${{ steps.tag_name.outputs.VERSION }}
          cp fapolicy-analyzer.spec $out
          sed -z -i -e "s#fapolicy-analyzer.tar.gz#$base/fapolicy-analyzer.tar.gz#" $out
          sed -z -i -e "s#vendor-docs.tar.gz#$base/vendor-docs.tar.gz#" $out
          sed -z -i -e "s#vendor-rs.tar.gz#$base/vendor-rs.tar.gz#" $out
          sed    -i -e "s#vendor-rs.tar.gz#vendor-rs%{?dist}.tar.gz#" $out

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.VERSION }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
          draft: true
          files: |
            /tmp/archives/*.rpm
            /tmp/archives/*.spec
            /tmp/archives/*.tar.gz
