on:
  push:
    branches:
      - 'master'
      - 'release/*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: Rust CI

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: 1.62.1
      - run: rustup component add rustfmt
      - run: touch crates/auparse/sys/src/bindings.rs
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.62.1
      - uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: 1.62.1
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: Test Suite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.62.1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
