on:
  push:
    branches:
      - 'master'
      - 'release/*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

name: Rust CI

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: 1.66.1
      - run: rustup component add rustfmt
      # use a placeholder for bindgen bindings
      - run: echo "//placeholder" | tee crates/auparse/sys/src/bindings.rs
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.66.1
      - uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # disable lint on pyo3 due to
      # https://github.com/rust-lang/rust-clippy/issues/8971
      - run: sed -i '/pyo3/d' Cargo.toml

      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: 1.66.1
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  semver-checks:
    name: Semver Check
    runs-on: ubuntu-latest
    steps:
      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: actions/checkout@v3
      - name: Check semver
        uses: u9g/cargo-semver-checks-action
        with:
          pr: true
          verbose: true

  test:
    name: Test Suite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libaudit-dev libauparse-dev
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.66.1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
